#!/bin/bash
function func() {
echo "HOSTNAME=$(hostname)"
#echo "HOSTNAME = $HOSTNAME"
echo "TIMEZONE=$(timedatectl | grep 'Time zone' | awk '{print $3}')"
echo "UTC=$(date +%z)"
#echo "TIMEZONE = $TIMEZONE $UTC"
echo "USER=$(whoami)"
#echo "USER = $USER"
echo "OS=$(cat /etc/issue)"
#echo "OS = $OS"
echo "DATE=$(date +"%d %B %Y %T")"
echo "UPTIME=$(uptime -p)"
echo "UPTIME_SEC=$(cat /proc/uptime | awk '{print $1}')"
echo "IP=$(ip a | grep -m 1 'inet' |  awk '{print $2}')"
echo "MASK=$(ifconfig | grep 'netmask' | awk '{print $4}')"
echo "GATEWAY=$(ip route | grep default | awk '{print $3}')"
echo "RAM_TOTAL=$(free -h | grep Mem | awk '{printf("%.3f", $2)}')"
echo "RAM_USED=$(free -h | grep Mem | awk '{printf("%.3f", $3)}')"
echo "RAM_FREE=$(free -h | grep Mem | awk '{printf("%.3f", $4)}')"
echo "SPACE_ROOT=$(df -m / | awk '{printf("%.2f", $2)}')"
echo "SPACE_ROOT_USED=$(df -m / | awk '{printf("%.2f", $3)}')"
echo "SPACE_ROOT_FREE=$(df -m / | awk '{printf("%.2f", $4)}')"
}
